import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import htm from 'htm';
import {Puck,FieldLabel} from '@puckeditor/core';

const html=htm.bind(React.createElement);
const KEYS={page:'jinhuan_puck_page_v2',products:'jinhuan_products_v2',settings:'jinhuan_settings_v2'};
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const uid=()=>Math.random().toString(36).slice(2,10);
const fileData=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});
const text=label=>({type:'text',label});
const textarea=label=>({type:'textarea',label});
const number=(label,min,max)=>({type:'number',label,min,max});
const select=(label,options)=>({type:'select',label,options:options.map(([label,value])=>({label,value}))});

function ImageUploadField({field,value,onChange}){return html`<${FieldLabel} label=${field.label||'图片'}><div className="jh-custom-field">${value?html`<img src=${value} alt="preview"/>`:html`<div className="jh-note">还没有图片</div>`}<input type="file" accept="image/*" onChange=${async e=>{const f=e.currentTarget.files?.[0];if(f)onChange(await fileData(f));}}/><input type="text" placeholder="或粘贴图片 URL" value=${value||''} onChange=${e=>onChange(e.currentTarget.value)}/></div></${FieldLabel}>`}
const imageField={type:'custom',label:'图片',render:ImageUploadField};

const defaultSettings={brand:'JINHUAN',email:'',whatsapp:'',telegram:''};
const defaultProducts=[
{id:'demo1',name:'Structured Top Handle',sku:'JH-001',category:'Top Handle',size:'22 × 14 × 8 cm',color:'Black',image:'',status:'active'},
{id:'demo2',name:'Ivory Mini Bag',sku:'JH-002',category:'Mini',size:'19 × 12 × 7 cm',color:'Ivory',image:'',status:'active'},
{id:'demo3',name:'Soft Shoulder Bag',sku:'JH-003',category:'Shoulder',size:'24 × 16 × 9 cm',color:'Brown',image:'',status:'active'}
];
const defaultPage={content:[
{type:'Announcement',props:{id:'ann1',text:'WORLDWIDE HANDBAG CATALOGUE · DIRECT INQUIRY AVAILABLE'}},
{type:'Header',props:{id:'head1',brand:'JINHUAN',menu1:'Collection',menu2:'New Arrivals',menu3:'About',menu4:'Contact',button:'INQUIRE'}},
{type:'CollectionIntro',props:{id:'intro1',eyebrow:'THE COLLECTION',title:'Handbags selected for modern elegance.',intro:'Category names, products, product count and image layout can all be customized.'}},
{type:'CategoryBar',props:{id:'cat1',all:'ALL',cat1:'TOP HANDLE',cat2:'SHOULDER',cat3:'CROSSBODY',cat4:'MINI',cat5:'TOTE'}},
{type:'ProductGrid',props:{id:'grid1',columns:3,count:9,ratio:'3/4',gap:18}},
{type:'Editorial',props:{id:'ed1',eyebrow:'ABOUT JINHUAN',title:'Quiet luxury, thoughtfully selected.',text:'Use this section for your collection story, service or brand introduction.',image:''}},
{type:'Contact',props:{id:'contact1',eyebrow:'CONTACT',title:'Interested in a product?',text:'Contact us directly for product details, availability and collection inquiries.'}},
{type:'Footer',props:{id:'foot1',brand:'JINHUAN',text:'© 2026 JINHUAN · Global Handbag Catalogue'}}
],root:{props:{}}};

function bagPlaceholder(tone='dark'){return html`<div className=${`jh-mini-bag ${tone}`}><i></i></div>`}

function makeConfig(products,settings){return {categories:{layout:{title:'页面模块',components:['Announcement','Header','CollectionIntro','CategoryBar','ProductGrid','Editorial','Contact','Footer']},media:{title:'图片',components:['ImageBlock']}},components:{
Announcement:{label:'顶部公告',fields:{text:text('公告文字')},defaultProps:{text:'WORLDWIDE HANDBAG CATALOGUE · DIRECT INQUIRY AVAILABLE'},render:p=>html`<div className="jh-announcement">${p.text}</div>`},
Header:{label:'导航栏',fields:{brand:text('品牌名称'),menu1:text('菜单 1'),menu2:text('菜单 2'),menu3:text('菜单 3'),menu4:text('菜单 4'),button:text('右侧按钮')},defaultProps:{brand:'JINHUAN',menu1:'Collection',menu2:'New Arrivals',menu3:'About',menu4:'Contact',button:'INQUIRE'},render:p=>html`<header className="jh-header"><strong>${p.brand}</strong><nav><a>${p.menu1}</a><a>${p.menu2}</a><a>${p.menu3}</a><a>${p.menu4}</a></nav><button>${p.button}</button></header>`},
CollectionIntro:{label:'系列标题',fields:{eyebrow:text('小标题'),title:textarea('大标题'),intro:textarea('右侧说明')},defaultProps:{eyebrow:'THE COLLECTION',title:'Handbags selected for modern elegance.',intro:'Category names, products, product count and image layout can all be customized.'},render:p=>html`<section className="jh-collection-head"><div><p className="jh-eyebrow">${p.eyebrow}</p><h1>${p.title}</h1></div><p>${p.intro}</p></section>`},
CategoryBar:{label:'分类按钮',fields:{all:text('全部'),cat1:text('分类 1'),cat2:text('分类 2'),cat3:text('分类 3'),cat4:text('分类 4'),cat5:text('分类 5')},defaultProps:{all:'ALL',cat1:'TOP HANDLE',cat2:'SHOULDER',cat3:'CROSSBODY',cat4:'MINI',cat5:'TOTE'},render:p=>html`<div className="jh-filters">${[p.all,p.cat1,p.cat2,p.cat3,p.cat4,p.cat5].filter(Boolean).map((x,i)=>html`<button className=${i===0?'active':''}>${x}</button>`)}</div>`},
ProductGrid:{label:'商品区',fields:{columns:number('每行商品数量',2,5),count:number('显示商品数量',1,30),ratio:select('图片比例',[['1 : 1','1/1'],['4 : 5','4/5'],['3 : 4','3/4']]),gap:number('商品间距 px',0,40)},defaultProps:{columns:3,count:9,ratio:'3/4',gap:18},render:p=>{const list=products.filter(x=>x.status!=='draft').slice(0,p.count||9);return html`<section className="jh-product-section"><div className="jh-product-grid" style=${{gridTemplateColumns:`repeat(${p.columns||3},minmax(0,1fr))`,gap:`${p.gap??18}px`}}>${list.map((x,i)=>html`<article className="jh-product-card" key=${x.id}><div className="jh-product-photo" style=${{aspectRatio:p.ratio||'3/4'}}>${x.image?html`<img src=${x.image} alt=${x.name}/>`:bagPlaceholder(i%3===1?'light':i%3===2?'brown':'dark')}</div><div className="jh-product-copy"><h3>${x.name}</h3><p>${x.sku}${x.size?' · '+x.size:''}</p></div></article>`)}</div></section>`}},
Editorial:{label:'品牌图文',fields:{eyebrow:text('小标题'),title:textarea('标题'),text:textarea('正文'),image:imageField},defaultProps:{eyebrow:'ABOUT JINHUAN',title:'Quiet luxury, thoughtfully selected.',text:'Use this section for your collection story, service or brand introduction.',image:''},render:p=>html`<section className="jh-editorial"><div className="jh-editorial-art">${p.image?html`<img src=${p.image} alt="About"/>`:bagPlaceholder('dark')}</div><div className="jh-editorial-copy"><p className="jh-eyebrow">${p.eyebrow}</p><h2>${p.title}</h2><p>${p.text}</p></div></section>`},
Contact:{label:'联系区',fields:{eyebrow:text('小标题'),title:textarea('标题'),text:textarea('正文')},defaultProps:{eyebrow:'CONTACT',title:'Interested in a product?',text:'Contact us directly for product details, availability and collection inquiries.'},render:p=>html`<section className="jh-contact"><p className="jh-eyebrow">${p.eyebrow}</p><h2>${p.title}</h2><p>${p.text}</p><div><a href=${settings.email?`mailto:${settings.email}`:'#'}>EMAIL US</a><a href="#">WHATSAPP</a><a href="#">TELEGRAM</a></div></section>`},
Footer:{label:'页脚',fields:{brand:text('品牌'),text:text('版权')},defaultProps:{brand:'JINHUAN',text:'© 2026 JINHUAN · Global Handbag Catalogue'},render:p=>html`<footer className="jh-footer"><strong>${p.brand}</strong><small>${p.text}</small></footer>`},
ImageBlock:{label:'自由图片',fields:{image:imageField,height:number('高度 px',120,1000),fit:select('显示方式',[['填满裁切','cover'],['完整显示','contain']]),x:number('左右位置 %',0,100),y:number('上下位置 %',0,100)},defaultProps:{image:'',height:520,fit:'cover',x:50,y:50},render:p=>html`<div className="jh-image-block" style=${{height:`${p.height||520}px`}}>${p.image?html`<img src=${p.image} style=${{objectFit:p.fit||'cover',objectPosition:`${p.x??50}% ${p.y??50}%`}}/>`:html`<span>在右侧上传图片</span>`}</div>`}
},root:{render:({children})=>html`<div className="jh-storefront">${children}</div>`}}}

function ProductManager({products,setProducts}){const blank={name:'',sku:'',category:'',size:'',material:'',color:'',description:'',image:'',status:'active'};const[draft,setDraft]=useState(blank);const[editId,setEditId]=useState(null);const save=e=>{e.preventDefault();if(!draft.name||!draft.sku)return alert('请填写商品名称和 SKU');const item={...draft,id:editId||uid()};const next=editId?products.map(x=>x.id===editId?item:x):[item,...products.filter(x=>!x.id.startsWith('demo'))];setProducts(next);write(KEYS.products,next);setDraft(blank);setEditId(null)};return html`<div className="jh-panel"><div className="jh-pagehead"><div><h1>商品管理</h1><p>这里添加的商品会直接出现在上面的三列商品区。</p></div></div><form className="jh-card jh-product-form" onSubmit=${save}>${[['商品名称','name'],['SKU','sku'],['分类','category'],['尺寸','size'],['材质','material'],['颜色','color']].map(([l,k])=>html`<label>${l}<input value=${draft[k]||''} onInput=${e=>setDraft({...draft,[k]:e.currentTarget.value})}/></label>`)}<label className="jh-span2">商品描述<textarea value=${draft.description||''} onInput=${e=>setDraft({...draft,description:e.currentTarget.value})}></textarea></label><label>商品图片<input type="file" accept="image/*" onChange=${async e=>{const f=e.currentTarget.files?.[0];if(f)setDraft({...draft,image:await fileData(f)})}}/></label><label>状态<select value=${draft.status} onChange=${e=>setDraft({...draft,status:e.currentTarget.value})}><option value="active">上架</option><option value="draft">草稿</option></select></label><div className="jh-span2"><button className="jh-btn" type="submit">${editId?'保存修改':'新增商品'}</button></div></form><div className="jh-product-list">${products.map(x=>html`<article className="jh-admin-product" key=${x.id}><div>${x.image?html`<img src=${x.image}/>`:'暂无图片'}</div><section><h3>${x.name}</h3><p>${x.sku} · ${x.category||''}<br/>${x.size||''}</p><button onClick=${()=>{setDraft({...x});setEditId(x.id);window.scrollTo(0,0)}}>编辑</button>${!x.id.startsWith('demo')?html`<button className="danger" onClick=${()=>{const next=products.filter(p=>p.id!==x.id);setProducts(next);write(KEYS.products,next)}}>删除</button>`:null}</section></article>`)}</div></div>`}
function Settings(){const[s,setS]=useState(read(KEYS.settings,defaultSettings));return html`<div className="jh-panel"><div className="jh-pagehead"><div><h1>店铺设置</h1><p>品牌和联系方式。</p></div></div><div className="jh-card jh-settings">${[['网站名称','brand'],['联系邮箱','email'],['WhatsApp','whatsapp'],['Telegram','telegram']].map(([l,k])=>html`<label>${l}<input value=${s[k]||''} onInput=${e=>setS({...s,[k]:e.currentTarget.value})}/></label>`)}<button className="jh-btn" onClick=${()=>{write(KEYS.settings,s);alert('已保存')}}>保存设置</button></div></div>`}

function App(){const[view,setView]=useState('editor');const[products,setProducts]=useState(read(KEYS.products,defaultProducts));const settings=read(KEYS.settings,defaultSettings);const config=useMemo(()=>makeConfig(products,settings),[products]);const page=read(KEYS.page,defaultPage);return html`<div className="jh-shell"><header className="jh-topbar"><div className="jh-brand"><div className="jh-mark">JH</div><div><strong>JINHUAN Visual Editor</strong><small>保留原来的商品目录版式</small></div></div><nav className="jh-tabs">${[['editor','页面装修'],['products','商品管理'],['settings','店铺设置']].map(([k,l])=>html`<button className=${`jh-tab ${view===k?'active':''}`} onClick=${()=>setView(k)}>${l}</button>`)}</nav><a className="jh-open" href="../silex-demo/" target="_blank">查看原模板</a></header><main className="jh-main">${view==='editor'?html`<div className="jh-puck-wrap"><${Puck} config=${config} data=${page} viewports=${[{width:1440,label:'Desktop'},{width:768,label:'Tablet'},{width:390,label:'Mobile'}]} onChange=${data=>write(KEYS.page,data)} onPublish=${data=>{write(KEYS.page,data);alert('当前版式已保存到浏览器。')}} /></div>`:null}${view==='products'?html`<${ProductManager} products=${products} setProducts=${setProducts}/>`:null}${view==='settings'?html`<${Settings}/>`:null}</main></div>`}
createRoot(document.getElementById('root')).render(html`<${App}/>`);
